<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WSAMZN-MVKF1909" failures="4" tests="56" name="com.gapi.testCases.GetRemoteHandsTicketDetails" time="77.641" errors="10" timestamp="2023-05-19T18:18:41 IST" skipped="14">
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.846"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.800"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.783"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.841"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="0.811">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="0.457">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.026">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.923"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.749">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.233"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.187"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.842">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetRemoteHandsTicketInfoByInvalidId" time="0.401"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.821">
    <error message="JSONObject[&quot;category&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["category"] not found.
at org.json.JSONObject.get(JSONObject.java:520)
at org.json.JSONObject.getString(JSONObject.java:806)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:256)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.956">
    <error message="JSONObject[&quot;category&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["category"] not found.
at org.json.JSONObject.get(JSONObject.java:520)
at org.json.JSONObject.getString(JSONObject.java:806)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:282)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="getCategoryListForRemoteHandsRequestType" time="0.262"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="2.116">
    <error message="JSONObject[&quot;category&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["category"] not found.
at org.json.JSONObject.get(JSONObject.java:520)
at org.json.JSONObject.getString(JSONObject.java:806)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:282)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="getAllRemoteHandsTicketsInfo" time="0.325">
    <skipped/>
  </testcase> <!-- getAllRemoteHandsTicketsInfo -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.990">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.729"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.924">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.159"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.746"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="getAllRemoteHandsTicketsInfo" time="0.283">
    <failure message="expected [201] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [201] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.gapi.testCases.GetRemoteHandsTicketDetails.getAllRemoteHandsTicketsInfo(GetRemoteHandsTicketDetails.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getAllRemoteHandsTicketsInfo -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.783">
    <error message="JSONObject[&quot;category&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["category"] not found.
at org.json.JSONObject.get(JSONObject.java:520)
at org.json.JSONObject.getString(JSONObject.java:806)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:256)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.852"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.995"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="0.781">
    <error message="JSONObject[&quot;category&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["category"] not found.
at org.json.JSONObject.get(JSONObject.java:520)
at org.json.JSONObject.getString(JSONObject.java:806)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:282)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="0.540">
    <failure message="expected [Cancellation Requested] but found [Cancelled]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Cancellation Requested] but found [Cancelled]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:252)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.046"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="2.036"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="2.076">
    <error message="JSONObject[&quot;category&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["category"] not found.
at org.json.JSONObject.get(JSONObject.java:520)
at org.json.JSONObject.getString(JSONObject.java:806)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:282)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.781">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="getCategoryListForRemoteHandsRequestType" time="0.288"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.064"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="getCategoryListForRemoteHandsRequestType" time="0.290"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="0.481">
    <error message="A JSONObject text must begin with &#039;{&#039; at 0 [character 1 line 1]" type="org.json.JSONException">
      <![CDATA[org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
at org.json.JSONObject.<init>(JSONObject.java:214)
at org.json.JSONObject.<init>(JSONObject.java:357)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:233)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="2.128"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.969">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.886"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="0.525">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="2.347">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.942"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="0.968">
    <failure message="expected [25] but found [10]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [25] but found [10]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:270)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="0.534"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.862">
    <error message="JSONObject[&quot;category&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["category"] not found.
at org.json.JSONObject.get(JSONObject.java:520)
at org.json.JSONObject.getString(JSONObject.java:806)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:256)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.808"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.805">
    <error message="JSONObject[&quot;category&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["category"] not found.
at org.json.JSONObject.get(JSONObject.java:520)
at org.json.JSONObject.getString(JSONObject.java:806)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:282)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="2.118">
    <error message="JSONObject[&quot;category&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["category"] not found.
at org.json.JSONObject.get(JSONObject.java:520)
at org.json.JSONObject.getString(JSONObject.java:806)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:256)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.891">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="2.058"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.050"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="1.924"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="0.511">
    <failure message="expected [Cancellation Requested] but found [Cancelled]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Cancellation Requested] but found [Cancelled]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.gapi.testCases.GetRemoteHandsTicketDetails.verifyGetAllWithFilters(GetRemoteHandsTicketDetails.java:252)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="0.537"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.GetRemoteHandsTicketDetails" name="verifyGetAllWithFilters" time="0.555">
    <skipped/>
  </testcase> <!-- verifyGetAllWithFilters -->
  <system-out/>
</testsuite> <!-- com.gapi.testCases.GetRemoteHandsTicketDetails -->
